### ISSUE TITLE
Parameter Sweeps

### ISSUE THREAD

**Issue by ravi-mosaicml** [mosaicml/yahp#25]
The `'inherits` syntax does not work well for parameter sweeps. For example, consider someone is changing a sub-sub parameter, like the dataset path (e.g. options are AWS and cota) and then also a higher level parameter like precision (e.g. options are full and amp). To do this via the inheritance syntax while being as DRY as possible, I believe would have to define yaml files for 1) each dataset path, 2) each precision, and 3) each combination of dataset path and precision that specifies the proper inheritance (so this would be 2 + 2 + (2*2) = 8 yaml files).

One option is to use declarative merging of yaml files.

Or perhaps we don't have to support parameter sweeps in hparams; instead, that can be the job of the runner via cli overrides. 
(However, I would prefer for parameter sweeps to have first class support for yaml, as I find the format is much easier to read than the cli, and yaml files can be committed and version pinned).

**Comment by Averylamp** [comment]
This will be reworked in `mctl` and the infrastructure redesign
