### ISSUE TITLE
Utility to autogenerate hparams via introspection 

### ISSUE THREAD

**Issue by ravi-mosaicml** [mosaicml/yahp#57]
It would be nice to have a utility to autogenerate a hparams stub file for a class, given the signature of the init method

e.g.
```bash
yahp generate module.to.class:MyClass >  path/to/class_hparams.py
```

The autogenerated stub could include docstrings (parsed from the class's docstring), typing annotations (taken from the annotations of init), and a default `initialize_object()` that returns `MyClass(**asdict(self))`

**Comment by Averylamp** [comment]
See #97
